/* ═══════════════════════════════════════════
   GEMMINES2 — Product Catalog
   Add / edit products here. All pages read from this file.
   ═══════════════════════════════════════════ */
const PRODUCTS = [
  {
    "id": "sapphire-1780764315884",
    "name": "Natural P Color change Sapphire  Top eye clean Unheated  Color: From Violet to Purple",
    "shortName": "Natural P Color change Sapphire  Top eye clean Unheated  Color: From Violet to Purple",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Sri Lankan",
    "color": "Purple",
    "shape": "Oval Cut",
    "weight": 1.54,
    "dimensions": "",
    "clarity": "Eye Clean",
    "certificate": "Certificate Available",
    "price": 150,
    "pricePerCarat": 97,
    "status": "active",
    "rare": false,
    "description": "Discover the beauty of this natural unheated Color Change Sapphire from Sri Lanka, weighing 1.54 carats. This rare gemstone displays a stunning color shift from violet to rich purple under different lighting conditions. Featuring top eye-clean clarity and excellent natural brilliance, this sapphire is perfect for collectors, custom jewelry, or gemstone enthusiasts seeking a unique and elegant treasure.\n\n Natural Color Change Sapphire, Sri Lankan Sapphire, Unheated Sapphire, Violet Purple Sapphire, 1.54 ct Sapphire, Eye Clean Sapphire, Rare Sapphire Gemstone, Natural Sapphire Pakistan\n\n#ColorChangeSapphire #NaturalSapphire #SriLankanSapphire #UnheatedSapphire #PurpleSapphire #VioletSapphire #RareGemstone #EyeCleanSapphire #Gemstones #LooseGemstone #FineJewelry #CollectorGem #Gemmines",
    "gemType": "Sapphire",
    "images": [
      "images/natural-p-color-change-sapphire-top-1780765092779-0.jpg",
      "images/natural-p-color-change-sapphire-top-1780765094874-1.jpeg"
    ],
    "image": "images/natural-p-color-change-sapphire-top-1780765092779-0.jpg",
    "video": "videos/natural-p-color-change-sapphire-top-1780764311378.mp4"
  },
  {
    "id": "zircon-1780749358086",
    "name": "Beautifully handcrafted  exclusive pendant is made from genuine 925 sterling silver and set with a natural zircon and sparkling American diamonds.",
    "shortName": "Zircon",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Sri Lankan",
    "color": "Brownish",
    "shape": "Emerald Cut",
    "weight": 4,
    "dimensions": "",
    "clarity": "loupe clean",
    "certificate": "Available on Request",
    "price": 180,
    "pricePerCarat": 45,
    "status": "active",
    "rare": false,
    "description": "dsfffaffdd",
    "gemType": "Zircon",
    "images": [],
    "image": "",
    "video": "videos/beautifully-handcrafted-exclusive-p-1780749353470.mp4"
  },
  {
    "id": "chrysoberyl-1780742386216",
    "name": "Natural Chrysoberyl 1.35 ct - Loupe Clean, Certified Gemstone ( Sri Lankan )",
    "shortName": "Chrysoberyl",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Sri Lankan",
    "color": "Yellowish Green",
    "shape": "Oval Cut",
    "weight": 1.35,
    "dimensions": "",
    "clarity": "loupe clean",
    "certificate": "Certificate Available",
    "price": 120,
    "pricePerCarat": 89,
    "status": "active",
    "rare": false,
    "description": "Discover this exquisite natural chrysoberyl gemstone weighing 1.35 carats. Renowned for its exceptional hardness (8.5 on the Mohs scale) and brilliant luster, chrysoberyl is one of the most durable and sought-after gemstones, prized for its subtle honey-yellow to greenish hues and superior clarity.\nThis specimen is loupe-clean (eye-clean under 10x magnification), showcasing outstanding transparency and minimal inclusions for a radiant sparkle. Sourced from reputable origins known for quality chrysoberyl, it comes with a certificate of authenticity available upon request.\nPerfect for custom jewelry settings such as rings, pendants, or earrings, this versatile gem offers timeless elegance. Whether you're a collector or seeking a unique piece, its natural beauty and rarity make it a standout addition to any collection.",
    "gemType": "Chrysoberyl",
    "images": [
      "images/natural-chrysoberyl-1-35-ct-loupe-c-1780742383560-0.jpeg"
    ],
    "image": "images/natural-chrysoberyl-1-35-ct-loupe-c-1780742383560-0.jpeg",
    "video": ""
  },
  {
    "id": "zircon-1780734539709",
    "name": "Beautifully handcrafted exclusive pendant made from genuine 925 sterling silver and set with a natural zircon and sparkling American diamonds.",
    "shortName": "Zircon Pendant",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Sri Lankan",
    "color": "Brownish",
    "shape": "Emerald Cut",
    "weight": 4.001,
    "dimensions": "",
    "clarity": "loupe clean",
    "certificate": "Available on Request",
    "price": 179.99,
    "pricePerCarat": 45,
    "status": "active",
    "rare": false,
    "description": "Beautiful sterling silver setting with high-quality natural Zircon accent stone.",
    "gemType": "Zircon",
    "images": [],
    "image": "",
    "video": "videos/beautifully-handcrafted-exclusive-p-1780734535217.mp4"
  },
  {
    "id": "zircon-1780665881053",
    "name": "Beautifully handcrafted exclusive pendant is made from genuine 925 sterling silver and set with a natural zircon and sparkling American diamonds.",
    "shortName": "Blue Zircon",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Sri Lankan",
    "color": "Brownish",
    "shape": "Emerald Cut",
    "weight": 3.999,
    "dimensions": "",
    "clarity": "loupe clean",
    "certificate": "Certificate Available",
    "price": 95,
    "pricePerCarat": 24,
    "status": "active",
    "rare": true,
    "description": "Beautifully handcrafted exclusive pendant made from genuine 925 sterling silver, featuring a natural zircon gemstone enhanced with sparkling American diamonds. This elegant pendant offers a luxurious shine and timeless beauty, making it perfect for daily wear, gifting, or special occasions. Designed with fine craftsmanship and premium quality materials, this stylish silver pendant adds sophistication and charm to any jewelry collection. A perfect choice for those who appreciate classic elegance and modern sparkle.\n925 sterling silver pendant, natural zircon pendant, zircon jewelry, American diamond pendant, handcrafted silver jewelry, luxury pendant for women, gemstone pendant, elegant silver necklace, Pakistan jewelry, exclusive zircon pendant\n\n\n#SterlingSilver #925Silver #ZirconPendant #NaturalZircon #SilverJewelry #AmericanDiamond #HandcraftedJewelry #LuxuryPendant #GemstoneJewelry #ElegantStyle #FashionJewelry #PendantDesign #JewelryLovers #SilverPendant #ExclusiveJewelry",
    "gemType": "Zircon",
    "images": [
      "images/zircon-pendant-1780665878476-0.jpeg"
    ],
    "image": "images/zircon-pendant-1780665878476-0.jpeg",
    "video": ""
  },
  {
    "id": "spinel-1780499911496",
    "name": "Natural Sri Lankan( Ceylon ) Blue Spinel 1 Carat | Loupe / Eye Clean Unheated Gemstone",
    "shortName": "Natural Spinel",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Sri Lanka",
    "color": "Blue",
    "shape": "oval shape",
    "weight": 1,
    "dimensions": "",
    "clarity": "loupe clean",
    "certificate": "Available on Request",
    "price": 125,
    "pricePerCarat": 125,
    "status": "active",
    "rare": false,
    "description": "Natural Sri Lankan Blue Spinel with pristine loupe clean clarity.",
    "gemType": "Spinel",
    "images": [
      "images/natural-sri-lankan-ceylon-blue-spin-1780499908961-0.jpg"
    ],
    "image": "images/natural-sri-lankan-ceylon-blue-spin-1780499908961-0.jpg"
  },
  {
    "id": "garnet-1780215589223",
    "name": "Natural Unheated Rhodolite Garnets 12.2 Carats",
    "shortName": "Rhodolite Garnets",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Tanzania",
    "color": "Reddish Pink",
    "shape": "Oval, Cushion, Rectangular",
    "weight": 12.2,
    "dimensions": "",
    "clarity": "Loupe Clean",
    "certificate": "Available on Request",
    "price": 200,
    "pricePerCarat": 16,
    "status": "active",
    "rare": false,
    "description": "Natural Unheated Rhodolite Garnets from Tanzania. Mixed cuts including oval, cushion and rectangular shapes. Reddish pink color with excellent luster and loupe clean clarity.",
    "gemType": "Garnet",
    "images": [
      "images/rhodolite-garnets-1780215583524-0.jpg"
    ],
    "image": "images/rhodolite-garnets-1780215583524-0.jpg"
  },
  {
    "id": "greenjasper_005",
    "name": "Natural Green Jasper Stones 10+ Carats",
    "shortName": "Green Jasper",
    "type": "rough",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Green",
    "shape": "Rough/Tumbled",
    "weight": 10,
    "dimensions": "",
    "clarity": "Opaque",
    "certificate": "Available on Request",
    "price": 100,
    "pricePerCarat": 10,
    "status": "active",
    "rare": false,
    "description": "Opaque quality green jasper from Pakistan with beautiful lustre and color.",
    "gemType": "Jasper",
    "images": [
      "images/green-jasper.jpg"
    ],
    "image": "images/green-jasper.jpg"
  },
  {
    "id": "lemonquartz_012",
    "name": "Natural Unheated Lemon Quartz 11.15 Carats",
    "shortName": "Lemon Quartz",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Lemon Yellow",
    "shape": "Faceted",
    "weight": 11.15,
    "dimensions": "",
    "clarity": "Eye Clean",
    "certificate": "Available on Request",
    "price": 70,
    "pricePerCarat": 6,
    "status": "active",
    "rare": false,
    "description": "Vibrant Lemon Quartz from Pakistan. Stone of clarity and positive energy with eye clean transparency.",
    "gemType": "Quartz",
    "images": [
      "images/lemon-quartz.jpg"
    ],
    "image": "images/lemon-quartz.jpg"
  },
  {
    "id": "lemonquartz2_014",
    "name": "Natural Eye-Clean Lemon Quartz Cut and Polished",
    "shortName": "Lemon Quartz AAA",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Lemon Yellow",
    "shape": "Faceted",
    "weight": 8.5,
    "dimensions": "",
    "clarity": "AAA Eye Clean",
    "certificate": "Available on Request",
    "price": 140,
    "pricePerCarat": 16,
    "status": "active",
    "rare": false,
    "description": "AAA Grade Faceted Lemon Quartz Loose Stone from Pakistan with exceptional clarity and brilliant cut.",
    "gemType": "Quartz",
    "images": [
      "images/lemon-quartz2.jpg"
    ],
    "image": "images/lemon-quartz2.jpg"
  },
  {
    "id": "bluesapphire_016",
    "name": "Stunning Sri Lankan Blue Sapphire Heated 1.10 Carats",
    "shortName": "Blue Sapphire",
    "type": "cut",
    "treatment": "heated",
    "origin": "Sri Lanka",
    "color": "Blue",
    "shape": "Faceted",
    "weight": 1.1,
    "dimensions": "",
    "clarity": "Transparent",
    "certificate": "Available on Request",
    "price": 320,
    "pricePerCarat": 291,
    "status": "active",
    "rare": false,
    "description": "Symbol of wisdom, virtue and good fortune. Stunning blue sapphire from Sri Lanka with heat treatment for enhanced color.",
    "gemType": "Sapphire",
    "images": [
      "images/bluesapphire.jpg"
    ],
    "image": "images/bluesapphire.jpg"
  },
  {
    "id": "emeralds_017",
    "name": "Natural Unheated Cut and Polished Zambian Emeralds",
    "shortName": "Zambian Emeralds",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Zambia",
    "color": "Rich Green",
    "shape": "Faceted",
    "weight": 2.4,
    "dimensions": "",
    "clarity": "Transparent",
    "certificate": "Available on Request",
    "price": 600,
    "pricePerCarat": 250,
    "status": "active",
    "rare": true,
    "description": "Premium Untreated Loose Gemstones with Rich Green Hue from Zambia. Natural unheated emeralds with exceptional color saturation.",
    "gemType": "Emerald",
    "images": [
      "images/emeralds.jpg"
    ],
    "image": "images/emeralds.jpg"
  },
  {
    "id": "fluorite_018",
    "name": "Natural Unheated Blue Fluorite 58 Carats",
    "shortName": "Blue Fluorite",
    "type": "rough",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Blue",
    "shape": "Polished Crystal",
    "weight": 58,
    "dimensions": "",
    "clarity": "High Clarity",
    "certificate": "Available on Request",
    "price": 100,
    "pricePerCarat": 2,
    "status": "active",
    "rare": false,
    "description": "Rare High Clarity Polished Crystal Healing Stone from Pakistan. Beautiful blue fluorite with exceptional clarity.",
    "gemType": "Fluorite",
    "images": [
      "images/fluorite.jpg"
    ],
    "image": "images/fluorite.jpg"
  },
  {
    "id": "mixedgemstones_019",
    "name": "Natural Mixed Lot Gemstones Peridot Garnet and Smoky Quartz",
    "shortName": "Mixed Gemstones",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Multi-Color",
    "shape": "Mixed Cuts",
    "weight": 15.3,
    "dimensions": "",
    "clarity": "Transparent",
    "certificate": "Available on Request",
    "price": 600,
    "pricePerCarat": 39,
    "status": "active",
    "rare": false,
    "description": "Collection of rare mixed gemstones including Peridot, Garnet and Smoky Quartz. Perfect for collectors.",
    "gemType": "Mixed",
    "images": [
      "images/mixed-gemstones.jpg"
    ],
    "image": "images/mixed-gemstones.jpg"
  },
  {
    "id": "almandine_028",
    "name": "Natural Almandine Garnet 60 Carat Oval Cut",
    "shortName": "Almandine Garnet",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Reddish Purple",
    "shape": "Oval Cut",
    "weight": 60,
    "dimensions": "",
    "clarity": "Transparent",
    "certificate": "Available on Request",
    "price": 125,
    "pricePerCarat": 2,
    "status": "active",
    "rare": false,
    "description": "Polished Reddish Purple Almandine Garnet from Pakistan. Unheated and Untreated with beautiful oval cut.",
    "gemType": "Garnet",
    "images": [
      "images/almandine.jpg"
    ],
    "image": "images/almandine.jpg"
  },
  {
    "id": "mixed_sapphire_029",
    "name": "Premium Mixed Sapphire Collection Multi-Color",
    "shortName": "Mixed Sapphires",
    "type": "rough",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Multi-Color",
    "shape": "Loose Uncut",
    "weight": 22.1,
    "dimensions": "",
    "clarity": "Transparent/Translucent",
    "certificate": "Available on Request",
    "price": 400,
    "pricePerCarat": 18,
    "status": "active",
    "rare": false,
    "description": "Natural multi-color loose sapphire gemstones from Pakistan. Beautiful collection of unheated sapphires in various colors.",
    "gemType": "Sapphire",
    "images": [
      "images/mixedsapphire.jpg"
    ],
    "image": "images/mixedsapphire.jpg"
  },
  {
    "id": "Natural_Black_Chert_030",
    "name": "Natural Black Chert Tumbled Stone from Pakistan",
    "shortName": "Black Chert",
    "type": "rough",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Deep Black",
    "shape": "Tumbled Stone",
    "weight": 14,
    "dimensions": "",
    "clarity": "Opaque",
    "certificate": "Available on Request",
    "price": 80,
    "pricePerCarat": 5,
    "status": "active",
    "rare": false,
    "description": "Smooth river rock specimen with deep black color from Pakistan. Natural tumbled chert stone.",
    "gemType": "Chert",
    "images": [
      "images/chert.jpg"
    ],
    "image": "images/chert.jpg"
  },
  {
    "id": "Kunzite_031",
    "name": "Natural Pink Kunzite Gemstone 4.80 Carats",
    "shortName": "Pink Kunzite",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Pink",
    "shape": "Oval Cut",
    "weight": 4.8,
    "dimensions": "",
    "clarity": "Transparent",
    "certificate": "Available on Request",
    "price": 100,
    "pricePerCarat": 21,
    "status": "active",
    "rare": false,
    "description": "Unheated transparent oval-cut natural pink kunzite from Pakistan. Beautiful pink color with excellent transparency.",
    "gemType": "Kunzite",
    "images": [
      "images/pink-kunzite.jpg"
    ],
    "image": "images/pink-kunzite.jpg"
  },
  {
    "id": "quartz_034",
    "name": "12 Carat Ferruginous Quartz Gemstone",
    "shortName": "Ferruginous Quartz",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Yellow/White",
    "shape": "Loose Stone",
    "weight": 12,
    "dimensions": "",
    "clarity": "Translucent",
    "certificate": "Available on Request",
    "price": 70,
    "pricePerCarat": 6,
    "status": "active",
    "rare": false,
    "description": "Vibrant Yellow with White Hues. Natural Loose Ferruginous Quartz Stone from Pakistan.",
    "gemType": "Quartz",
    "images": [
      "images/ferruginous.jpg"
    ],
    "image": "images/ferruginous.jpg"
  },
  {
    "id": "sapphire_039",
    "name": "2.15ct Natural Unheated Bi-Color Sapphire Sri Lanka",
    "shortName": "Bi-Color Sapphire",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Sri Lanka",
    "color": "Bi-Color",
    "shape": "Pear Cut",
    "weight": 2.15,
    "dimensions": "",
    "clarity": "Transparent",
    "certificate": "Available on Request",
    "price": 95,
    "pricePerCarat": 44,
    "status": "active",
    "rare": true,
    "description": "Rare Sri Lankan Origin Bi-Color Sapphire. Unheated and untreated with pear cut. Beautiful two-tone color combination.",
    "gemType": "Sapphire",
    "images": [
      "images/bi-color-sapphire.jpeg"
    ],
    "image": "images/bi-color-sapphire.jpeg"
  },
  {
    "id": "sapphire_040",
    "name": "5.80ct Royal Blue Sapphire Sri Lankan Origin",
    "shortName": "Royal Blue Sapphire",
    "type": "cut",
    "treatment": "heated",
    "origin": "Sri Lanka",
    "color": "Royal Blue",
    "shape": "Oval Brilliant Cut",
    "weight": 5.8,
    "dimensions": "",
    "clarity": "Transparent",
    "certificate": "Available on Request",
    "price": 120,
    "pricePerCarat": 21,
    "status": "active",
    "rare": false,
    "description": "Heated Royal Blue Sapphire from Sri Lanka with Oval Brilliant Cut. Deep royal blue color with excellent luster.",
    "gemType": "Sapphire",
    "images": [
      "images/darksapphire.jpeg"
    ],
    "image": "images/darksapphire.jpeg"
  },
  {
    "id": "sapphire_043",
    "name": "Heated Padparadscha Sapphire 2.93 Carats Sri Lanka",
    "shortName": "Padparadscha Sapphire",
    "type": "cut",
    "treatment": "heated",
    "origin": "Sri Lanka",
    "color": "Pink-Orange",
    "shape": "Faceted",
    "weight": 2.93,
    "dimensions": "",
    "clarity": "Transparent",
    "certificate": "Available on Request",
    "price": 190,
    "pricePerCarat": 65,
    "status": "active",
    "rare": true,
    "description": "Sri Lankan Ceylon Pink-Orange Padparadscha Sapphire with Beautiful Luster. One of the rarest sapphire varieties in the world.",
    "gemType": "Sapphire",
    "images": [
      "images/Padparadscha-sapphire.jpeg"
    ],
    "image": "images/Padparadscha-sapphire.jpeg"
  },
  {
    "id": "ruby_044",
    "name": "Natural Unheated Sri Lankan Ruby 1.06 Carats",
    "shortName": "Ceylon Ruby",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Sri Lanka",
    "color": "Vivid Red",
    "shape": "Faceted",
    "weight": 1.06,
    "dimensions": "",
    "clarity": "Transparent",
    "certificate": "Available on Request",
    "price": 200,
    "pricePerCarat": 189,
    "status": "active",
    "rare": true,
    "description": "Vivid Red Ceylon Ruby Gemstone with Stunning Luster. Natural unheated Sri Lankan ruby, one of the most sought after gemstones in the world.",
    "gemType": "Ruby",
    "images": [
      "images/ruby2.jpeg"
    ],
    "image": "images/ruby2.jpeg"
  },
  {
    "id": "pinktopaz_101",
    "name": "Natural Unheated Pink Topaz 18 Carats Pakistan",
    "shortName": "Pink Topaz",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Light Pink",
    "shape": "Emerald Cut",
    "weight": 18,
    "dimensions": "",
    "clarity": "Eye Clean with Minor Natural Inclusion",
    "certificate": "Available on Request",
    "price": 120,
    "pricePerCarat": 7,
    "status": "active",
    "rare": false,
    "description": "Natural Unheated Light Pink Topaz from Pakistan weighing 18.00 carats. Soft light pink color with minor natural inclusions confirming authenticity.",
    "gemType": "Topaz",
    "images": [
      "images/pinktopaz.gif",
      "images/natural-unheated-pink-topaz-18-cara-1780319473513-0.jpg",
      "images/natural-unheated-pink-topaz-18-cara-1780319477585-1.jpg"
    ],
    "image": "images/pinktopaz.gif"
  },
  {
    "id": "Greenperidot_102",
    "name": "Natural Unheated Olive Green Peridot Pakistan",
    "shortName": "Olive Peridot",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Olive Green",
    "shape": "Oval",
    "weight": 5,
    "dimensions": "",
    "clarity": "Eye Clean with Natural Rutile",
    "certificate": "Available on Request",
    "price": 95,
    "pricePerCarat": 19,
    "status": "active",
    "rare": false,
    "description": "Natural unheated olive green peridot from Pakistan with attractive color and good luster.",
    "gemType": "Peridot",
    "images": [
      "images/peridot.gif"
    ],
    "image": "images/peridot.gif"
  },
  {
    "id": "rhodolitegarnets_103",
    "name": "Natural Unheated Rhodolite Garnets 12 Carats Tanzania",
    "shortName": "Rhodolite Garnets",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Tanzania",
    "color": "Reddish Pink",
    "shape": "Mixed Cuts",
    "weight": 12,
    "dimensions": "",
    "clarity": "Transparent",
    "certificate": "Available on Request",
    "price": 140,
    "pricePerCarat": 12,
    "status": "active",
    "rare": false,
    "description": "Natural unheated rhodolite garnets from Tanzania featuring mixed gemstone cuts, reddish pink color, and good luster.",
    "gemType": "Garnet",
    "images": [
      "images/rhodolite.jpg"
    ],
    "image": "images/rhodolite.jpg"
  },
  {
    "id": "jade_045",
    "name": "Natural Translucent Green Nephrite Jade Gemstone 3.20 Carats Pakistan",
    "shortName": "Green Jade",
    "type": "cut",
    "treatment": "unheated",
    "origin": "Pakistan",
    "color": "Translucent Green",
    "shape": "Oval Cut",
    "weight": 3.2,
    "dimensions": "",
    "clarity": "Translucent",
    "certificate": "Available on Request",
    "price": 80,
    "pricePerCarat": 25,
    "status": "active",
    "rare": false,
    "description": "Discover this beautiful natural translucent green nephrite gemstone from Pakistan. Untreated and unenhanced gemstone features the classic silky texture and toughness that nephrite is famous for.",
    "gemType": "Jade",
    "images": [
      "images/natural-translucent-green-nephrite--1780761893401-0.jpg",
      "images/natural-translucent-green-nephrite--1780761897176-1.jpg"
    ],
    "image": "images/natural-translucent-green-nephrite--1780761893401-0.jpg",
    "video": ""
  }
];
